### ISSUE TITLE
PDP Popup: Recommended Products and Recently Viewed - Tab and Quick View

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#10]
Recommended Products: Full product info, Tab Functionality(Quick View, Publication, Review-almost similar to Overview)
Recently Viewed: almost similar to recommended products

**Comment by Rajesh-GSPANN** [comment]
Hi ,
Started Working on the issue. Looking PDP API call to reuse the response.

CC: @Meenu-GSPANN

**Comment by Rajesh-GSPANN** [comment]
Hi @davidzochowski ,

While fetching the details of the Product Detail Page (PDP), we are receiving the following fields: 'images', 'publicationsjson', and other fields. To filter the images or publications based on the selected 'Application' and 'Species' filters, we need to have a mapping of the fields. Could you please provide the necessary information to enable filtering based on these criteria?

Additionally, we need to know which fields to use to display the Reviews and Ratings, as well as the mappings required to filter the Reviews upon selecting the 'Application' and 'Species' filters.
Please let us know we can schedule a call to discuss more on this.

CC: @Meenu-GSPANN  @rgravitvl  @sharanagoudapatil  @amlan18041996

**Comment by davidzochowski** [comment]
Hi Rajesh, 

I have added the reactivity and species fields as part of the publicationsjson object.
The imagesjson object already has those fields so you should be able to build that section immediately.

I have started a rebuild. You should start seeing the data come through over time.

One thing to note, to fix an issue where the json list fields were nonparseable, I have made publicationsjson and imagesjson into a single string field. You will need to do a slight modification with how you are reading the fields.

**Comment by Rajesh-GSPANN** [comment]
Thanks for the update @davidzochowski ,
How about the reviews and ratings part ?

CC: @Meenu-GSPANN  @davenichols-DHLS  @rgravitvl  @amlan18041996  @pardeepgera23

**Comment by Rajesh-GSPANN** [comment]
Hi @davidzochowski ,
During our discussion, we determined that the Reviews and Ratings are fetched from a separate endpoint, which presents challenges in integrating the data into our system. As a result, we have decided to temporarily set aside the Reviews and Ratings section and will revisit it once we have the necessary details.
Now, we will proceed with implementing the Overview section and the Publication section.

CC: @davenichols-DHLS  @rgravitvl  @Meenu-GSPANN  @pardeepgera23  @amlan18041996 @venkateshamkeerthi @Naveen-Ramgiri

**Comment by Rajesh-GSPANN** [comment]
Hi @davidzochowski ,

I had a look into imagesJson object (product I used for analysis AB1791) and found that 
 1.Reactive species are not available for applications
  2. There are two image URLs we have 'url' and 'seoUrl' and these URLs are relative, we don't have complete path to the image.      and which one to use.
Can you please have a look into this .

CC: @davenichols-DHLS @rgravitvl @Meenu-GSPANN @pardeepgera23 @amlan18041996 @venkateshamkeerthi @Naveen-Ramgiri @shivangi1422 

Thanks!

**Comment by davidzochowski** [comment]
HI Rajesh, 

1. Not sure what you mean by this. Looking at the abcam page, images has only one filter and that is for application. This is present within the imagesjson.
2. Use the seoURL and prepend with https://content.abcam.com
Ex. https://content.abcam.com/products/images/histone-h3-antibody-nuclear-marker-and-chip-grade-ab1791--chip-img110703.jpg

**Comment by Rajesh-GSPANN** [comment]
Hi @davidzochowski ,
1. If we look at the Bottom right of the images , we see reactive Species, Even there are filtering on the Application filter. Attached screenshots for reference.
2. Sure, I will use seoURL. 

![All Application](https://github.com/user-attachments/assets/5d4966b3-84cf-4b6d-b6e9-27899989f947)
![Filter on application](https://github.com/user-attachments/assets/16f85481-bc3e-489a-b07f-9fddafb3466c)

 CC: @davenichols-DHLS @rgravitvl @Meenu-GSPANN @pardeepgera23 @amlan18041996 @venkateshamkeerthi @Naveen-Ramgiri @shivangi1422
 
 Thanks!

**Comment by Rajesh-GSPANN** [comment]
Hi ,
Implemented Bottom Section of the Overview section. Working on the responsive.

![image](https://github.com/user-attachments/assets/ba728e6a-dba9-4326-8aab-64357369ab00)

CC: @davidzochowski  @davenichols-DHLS @Meenu-GSPANN @amlan18041996 @pardeepgera23 @venkateshamkeerthi @Naveen-Ramgiri

**Comment by Rajesh-GSPANN** [comment]
Hi,
Able to show the image carousel. And filter them by application.
Working on the slide part.
![image](https://github.com/user-attachments/assets/ce009586-5e67-4eab-843f-02b11e77831c)


CC: @Meenu-GSPANN @pardeepgera23 @amlan18041996 @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi @davidzochowski ,
Did you get a chance to look into my query? that I have asked few days back (on August -16th). Can you please have a look into this and let us know.

CC: @davenichols-DHLS @Meenu-GSPANN @pardeepgera23 @venkateshamkeerthi @amlan18041996

**Comment by davidzochowski** [comment]
@Rajesh-GSPANN The Images json has both an 'application' and 'species' field defined for each image.
<img width="846" alt="Screenshot 2024-08-28 at 12 27 29 PM" src="https://github.com/user-attachments/assets/1ba93f36-a1be-4994-b0b7-6f1eb897bf6b">

**Comment by Rajesh-GSPANN** [comment]
Noted @davidzochowski . Thanks!

Hi,
Implemented the functionality and desktop design completed.
![image](https://github.com/user-attachments/assets/db48a5ec-481c-4901-938e-cb38e2181ebe)

CC: @davenichols-DHLS @Meenu-GSPANN  @pardeepgera23  @rgravitvl @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi,
PR yet to be raised, waiting for tother PRs to be merged.

**Comment by Rajesh-GSPANN** [comment]
Hi @rgravitvl,  @pardeepgera23 
Can you please review the [PR](https://github.com/aemsites/danaher-optimus/pull/220)
CC: @Meenu-GSPANN @amlan18041996 @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi,
PR is merged into Optimus repo, hence closing the ticket.

CC : @rgravitvl @pardeepgera23 @Meenu-GSPANN 

Thanks!
