### ISSUE TITLE
[Corporate] The Partnering Pages

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#109]
- [x] Analysis
- [ ] Design/Development

https://corporate.abcam.com/partnering/

**Comment by venkateshamkeerthi** [comment]
Analyzed https://corporate.abcam.com/partnering/ page below are Component details

</head>

<body link="#467886" vlink="#96607D">


Component   Name | Description
-- | --
Breadcrumb |  
Banner | with image background,   overlapping text with section component
2-Column | mostly first column 40% and   second column 60% and vice-versa
Section | 1. with background grey and   blue     2.text color black and white
Column-Table | Heading, Description and each   column have Image and description(with in section)
logo 4-Column |  
Banner with CTA | similar to above banner   component , we can achieve this functionality with single banner component
Scroll to Top |  



</body>

</html>

**Comment by venkateshamkeerthi** [comment]
analysis completed and updated, we will resume once design is completed
