### ISSUE TITLE
[Corporate] Our Latest News And Events Pages

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#122]
- [x] Analysis
- [ ] Design/Development

https://corporate.abcam.com/media-centre/our-latest-news
https://corporate.abcam.com/media-centre/events/

**Comment by VSriPalivela** [comment]
Analyzed https://corporate.abcam.com/media-centre/our-latest-news/ page below are Component details

1. **Breadcrumb** -> with the background of orange color. 
2. **Banner** -> It has a image as background and, overlay section/div as a second div and overlapping text with section component.
3. **Tab Component** -> Two tabs with first tab as active
3.1 Tab 01 -> **Slider** with four articles wrapper and each article has an href link which is redirected to whole article page along 
                         with background image
3.2 Tab 01 -> content-header and a date along with one href link as a read more button which is a whole article page link as 
                         same as above.
3.3 Tab 01 -> **Two column component** --
                        left column -> title section , search element, blog posts along with pagination functionality.
                        Right column -> Section which has heading and href link for twitter.
3.1 Tab 02 -> **ifram element** which is blocked right now 

4. **Two Column Component** -> Both columns has similar sections which has heading and sub heading along with subscribe 
                                                  button

**Comment by VSriPalivela** [comment]
Event Page : 

Breadcrumb -> with the background of orange color.

Banner -> It has a image as background and, overlay section/div as a second div and overlapping text with section component.

A section with background image which has 3 column cells inside of it which has a logo heading description and href link which is redirecting to home page 

A section with blue background and 2 column Component and one column has heading and sing-up today href link and second column has a question and a contact us
 : link which is redirecting to sing up

**Comment by VSriPalivela** [comment]
Closing this issue as analysis is completed once the development is started on these pages will reopen and work accordingly
