### ISSUE TITLE
[Corporate] About Page

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#123]
- [x] Analysis
- [ ] Design/Development

https://corporate.abcam.com/about/

**Comment by venkateshamkeerthi** [comment]
<body link="#467886" vlink="#96607D">


Component Name | Description | Assumption
-- | -- | --
Banner | similar to partnering page | Description in section is title of the page
Section(Intro) | similar to partnering page |  
Two Column | i)one of the column is embed   with video      ii)two column(1st column is image, 2nd column is title,description with  CTA and   two CTA) |  
3 column(background image/white color) | 1) 1st column 50% and other two   column 25%     2) 33.33% each column including animated number with CTA |  



</body>

</html>

**Comment by venkateshamkeerthi** [comment]
analysis completed and updated, we will resume once design is completed
