### ISSUE TITLE
[Corporate] Innovation Pages

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#124]
https://corporate.abcam.com/innovation/
- [x] Analysis
- [ ] Design/Development

**Comment by Rajesh-GSPANN** [comment]
Hi @Meenu-GSPANN ,
The analysis of the current site reveals that the majority of the pages within the Innovation section utilize the following elements:
	• Auto-Play Videos
	• Two-Column Layouts
		○ Rich Text
		○ Images
		○ Banner Backgrounds with Overlay Images
	• Accordion Components
	• Embedded Videos

To enhance efficiency, we should consider modifying these existing blocks for reuse. A decision on this can be made once the UX designs are finalized.

CC: @pardeepgera23 @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi @shivangi1422  @Meenu-GSPANN ,
As per our discussion I am closing the ticket. We will reopen the ticket , once we have latest designs and resume the development work.

CC: @pardeepgera23
