### ISSUE TITLE
Footer Changes

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#135]
The footer should look identical to the current Abcam footer:

![image](https://github.com/user-attachments/assets/ec27a2ce-517d-4fab-96c3-b4d42561303d)

**Comment by davenichols-DHLS** [comment]
@Meenu-GSPANN  - I have updated this task.

**Comment by Meenu-GSPANN** [comment]
Genedata is new addition to the footer. Please work on it
