### ISSUE TITLE
[Stories] Hub Page Tagging and Filters

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#136]
**FIGMA DESIGN**: https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Optimus-%2F-Abcam-Website-Designs?node-id=252-28&node-type=canvas&t=1Ypl4SZmeEt2PMIY-0

**OBJECTIVE**: Need to work on the filter functionality.

**RESOURCES**:
- Use `https://stage.lifesciences.danaher.com/us/en/products-index.json` URL.

**Comment by Meenu-GSPANN** [comment]
Filtering functionality completed including select & de-select options . Working on mock JSON API.

**Comment by amlan18041996** [comment]
**[ 25-09-2024 ]**: **Tagging** && **Filters** along with **single-clear-filter**, **group-clear-filter** and **all-clear-filter** feature. Working on mobile responsiveness and few bugs.

**[ 26-09-2024 ]**: Accessibility improvement, single-clear-filter and all-clear-filter bug resolved.

**[ 27-09-2024 ]**: mobile-responsiveness, clear-filter, show-less-selected filters, lint-issues, accordion toggler, backdrop and modal, show `filter` text on top only when there are any filters, show `clear-filter` only when there are any filters selected, show-more-or-less tags on mobile screen implemented.
