### ISSUE TITLE
[Stories]Hero Block Modification

### ISSUE THREAD

**Issue by shivangi1422** [aemsites/danaher-abcam#146]
https://go.myabcam.com/gina-poe-story?elqTrackId=99550817389d4f7290410007a3810e85&elq=00000000000000000000000000000000&elqaid=3756&elqat=2&elqCampaignId=&elqak=8AF593F50321B45C2843393B8AC546E1802079AED0F3B1C0DA87BA1BA3437B9834C7

https://go.myabcam.com/beyond-antibodies

UE Abcam Page:- https://main--danaher-abcam--aemsites.aem.page/en/stories/articles/beyond-antibodies

**Comment by Rajesh-GSPANN** [comment]
Hi @shivangi1422 ,
I have made the changes as we discussed , to show the title on the image. 
And I have pushed the [Code](https://github.com/aemsites/danaher-abcam/compare/main...146-hero-block-modification). If looks good I will raise PR
Please have a look at the [changes](https://146-hero-block-modification--danaher-abcam--aemsites.hlx.page/en/stories/articles/beyond-antibodies)

![Screenshot 2024-09-20 142513](https://github.com/user-attachments/assets/f48060fa-0f87-4cc7-af4d-ec64d69d4332)

CC: @Meenu-GSPANN @pardeepgera23 @rgravitvl

**Comment by Rajesh-GSPANN** [comment]
Hi @shivangi1422  @rgravitvl ,
I have raised [PR](https://github.com/aemsites/danaher-abcam/pull/151). Can you please review and merge.

CC: @pardeepgera23 @Meenu-GSPANN
