### ISSUE TITLE
Schemas for Stories Pages

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#149]
Within stories, where we have articles, we should add [article schema](https://urldefense.com/v3/__https://schema.org/Article__;!!G8Er-fQLpA!JxDZgcTmOWwC1aw-NZyirGvxB9D6eNgoZAN93kqHV3kwOsiKgg2xVUEKE1avGrFzSs69pFJ499rrcMDCRu7E8NcYG5rRwB4b$)
For videos, we should add [video schema](https://urldefense.com/v3/__https://schema.org/VideoObject__;!!G8Er-fQLpA!JxDZgcTmOWwC1aw-NZyirGvxB9D6eNgoZAN93kqHV3kwOsiKgg2xVUEKE1avGrFzSs69pFJ499rrcMDCRu7E8NcYG69TzoxU$)
If we also have podcasts, we can add podcast schema –
If entire podcast series is hosted on one page - [https://schema.org/PodcastSeries](https://urldefense.com/v3/__https://schema.org/PodcastSeries__;!!G8Er-fQLpA!JxDZgcTmOWwC1aw-NZyirGvxB9D6eNgoZAN93kqHV3kwOsiKgg2xVUEKE1avGrFzSs69pFJ499rrcMDCRu7E8NcYG7LBlIS8$)
If an episode is hosted on a page - [https://schema.org/PodcastEpisode](https://urldefense.com/v3/__https://schema.org/PodcastEpisode__;!!G8Er-fQLpA!JxDZgcTmOWwC1aw-NZyirGvxB9D6eNgoZAN93kqHV3kwOsiKgg2xVUEKE1avGrFzSs69pFJ499rrcMDCRu7E8NcYG545ny_s$)
 
You can validate schema code using this[ validator](https://urldefense.com/v3/__https://validator.schema.org/__;!!G8Er-fQLpA!JxDZgcTmOWwC1aw-NZyirGvxB9D6eNgoZAN93kqHV3kwOsiKgg2xVUEKE1avGrFzSs69pFJ499rrcMDCRu7E8NcYGwPsPgZG$).

**Comment by Meenu-GSPANN** [comment]
Thanks Dave for providing the information, Team started working on it, will provide update on Monday Call

**Comment by pardeepgera23** [comment]
Schemas have been updated and PR raised.
