### ISSUE TITLE
[Authoring Stories] Films

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#181]

**Comment by Rajesh-GSPANN** [comment]
Hi @rgravitvl ,
Below are the pages authored , can you please have a look.
[Joe beechem](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/joe-beechem)
[Alejandra solache](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/alejandra-solache)
[Graham heieis](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/graham-heieis)
[Virginia man yee lee](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/virginia-man-yee-lee)
[Robert blelloch](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/robert-blelloch)

And below are the two pages are not similar as the above pages. Can you please suggest how we can go ahead?
In partnership with:
[page 1](https://go.myabcam.com/gina-poe-story?elqTrackId=99550817389d4f7290410007a3810e85&elq=00000000000000000000000000000000&elqaid=3756&elqat=2&elqCampaignId=&elqak=8AF593F50321B45C2843393B8AC546E1802079AED0F3B1C0DA87BA1BA3437B9834C7)
[Page 2](https://go.myabcam.com/maryann-martone-story?elqTrackId=1782b1b9079148b6bd7e1ef5ee20523d&elq=00000000000000000000000000000000&elqaid=3756&elqat=2&elqCampaignId=&elqak=8AF5CA466501AA0B01534150C032980811A879AED0F3B1C0DA87BA1BA3437B9834C7)

CC: @davenichols-DHLS @pardeepgera23 @Meenu-GSPANN @shivangi1422  @VSriPalivela

**Comment by Rajesh-GSPANN** [comment]
Hi @rgravitvl ,
We authored the two pages can please have a look.
[Gina poe](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/gina-poe) -- We authored this page according to Figma design
[Maryann martone](https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/films/maryann-martone) -- We authored this page as per our discussion over the call.
Please let us know which looks good. We can modify other page.
