### ISSUE TITLE
[Stories] Stories Hub Issue with Filtering

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#194]
Thank you for working on the hub, looks great.  I noticed that there is an issue with the Stories Hub on filtering. 
 
If you select items and then remove, the filter breaks. 
 
For example:
 
Select “immunology-and-infectious-disease” and you see 3 items.
Then select “Film” you see 7 items.
Deselect “Film” and you see 29 items with just “immunology-and-infectious-disease” selected.
 
Would you be able to investigate this please?

**Comment by davenichols-DHLS** [comment]
FYI @pardeepgera23  and @Meenu-GSPANN

**Comment by pardeepgera23** [comment]
Closing as PR #200  is merged and filtering is working correctly now
