### ISSUE TITLE
Validation for Schemas

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#205]
ItemList schema – Looks good
Article schema –
For headline property, we see “When you hear the name Abcam, what comes to mind?” is used, which is H2. We recommend considering page H1 here.
For description – We prefer adding meta description here. But since there is no meta description present on the page, I believe the 1st paragraph of the article is taken as description.

**Comment by pardeepgera23** [comment]
For headline, we were earlier using meta title. I have updated to use h1 content from page now with fallback to meta title.

for description, we are using meta description only.
