### ISSUE TITLE
Remaining Podcast Issues

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#218]
- [x] Audio bar issue- Naveen
- [x] Video and audio are playing together - Rajesh
- [x] Fix the Spotify and Apple link with icon - Shivangi

**Comment by Rajesh-GSPANN** [comment]
Hi ,
Video and audio are playing together -> There are multiple scenarios to handle. Where we have to play one media at a time.
few of the scenario have been covered. 

CC : @Meenu-GSPANN @pardeepgera23 @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi,
Video and audio are playing together -> Raised PR and which includes minor UI fixes as well.

CC: @Meenu-GSPANN @pardeepgera23 @rgravitvl @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi @Meenu-GSPANN ,
in this task 218 - First one and two have been fixed and raised [PR](https://github.com/aemsites/danaher-abcam/pull/237).

@rgravitvl Please review and merge the code.

CC: @Naveen-Ramgiri @pardeepgera23
