### ISSUE TITLE
[Stories] Hub Page remaining issues

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#220]
- [x] Filtering refactoring **( AMLAN )**
- [x] Filters need to be in alphabetical order unless specified by the business **( AMLAN )**
- [x] Push the card listing down so it sits parallel to the facets **( AMLAN )**
- [x] Update the publication type text color to 65697C instead of #000000 and font to rockwell **( AMLAN )**
- [x] Apply 2 column/cards for resolution between 576px and 1024px **( AMLAN )**
- [x] Text color for the card's CTA needs to be corrected. Please update it to Abcam's green - #378189 **( AMLAN )**
- [x] Reduce the horizontal gap between cards/columns to 24px **( AMLAN )**
- [x] Font size for card sub text is incorrect **( AMLAN )**
- [x] Make the filters heading also clickable rather than limiting it only to the chevron icon **( AMLAN )**
- [x] The chevron icon for filters section. In collapsed state, it should be facing downwards and vice-versa **( AMLAN )**
- [x] On mobile and tablet devices, a black solid color appears around the image rather than covering it **( AMLAN )**
- [x] Sort all/filtered articles based on `publishDate`, from newest-date to oldest-date **( AMLAN )**
- [x] Carousal Auto Play issue **( SHIVANGI )**
- [x] Trying to scroll the page with the mouse cursor on the carousel, the hero image and carousel text scroll instead of the page **( SHIVANGI )**
- [x] Increase the page heading/title font size to 3.5rem (desktop) / 2.5 rem(mobile and tablet) and  add 40px gap between title and carousel **( SHIVANGI )**

**Comment by amlan18041996** [comment]
@shivangi1422 Carousel is absolutely fine on Chrome and Safari browser with URL: https://www.abcam.com/en-us/stories. Kindly pick any other task if you working on this.
