### ISSUE TITLE
[Stories] Article Remaining Issues

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#224]
- [X] 	The back link is not aligned. Please move it to the left so that it aligns with the start of the text. This applies to other pages, too.  ] Pending. On a bigger screens, it is still misaligned. Applicable to other pages too.
      : -->no code changes,working now, verified https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/articles/how-better-antibodies-can-save-time-in-the-lab 
- [x] 	The font for the 'Article' text should be Rockwell. This rule also applies to other pages.
- [x] Reduce the gap to 24px between the 'You may also be interested in...' heading and the cards. This rule applies to other pages, too
- [x] For tablet version, there is no padding on both the sides for ‘you may also interested in’ section
- [x] For related link section, please increase the gap between social media icons for share section to 16px. Same applies for share icons on the left column. Applicable to other pages too.
- [x]  For article text, please look into the spacing between paragraphs. It seems uneven.
- [x] 	On mobile: In the section with related links and share icons at the end of article, the button is appearing after the social media icons instead of below the text. 
- [x] On tablet portrait view, the ‘back to stories’ link is sticking to the header copy[bottom paddding 40px]
- [x] replace twitter icon with X
- [X] -You may interested section, please update the font for publication type to Rockwell and text color to #65697C
- [x]	The spacing/gap between sections should be 80px. It is more than 80px-need to investigate its common to all pages 
- [X]  the sub-text in the card is cropping on 1024px size(Tablet)
- [x] Related link section, tablet portrait mode (768px), social links should appear on a next link after the text and button. 
        Currently, they are placed next to each other and icons are too small 
- [x] You may be interested section heading is sticking to left edge on 1024px screen size
- [X] Hero module, the heading font should be 32px. Currently, it is 48px
- [X] You may be interested section, sub-text for card is cropping(mobile view)

https://github.com/aemsites/danaher-abcam/issues/211

**Comment by venkateshamkeerthi** [comment]
Pending Issues:
1.the gap between the 'You may also be interested in...' heading and the cards is still not 24 px. Its a bit more--?
discuss with team(all devices)-->related-stories
2. The spacing/gap between sections should be 80px. It is more than 80px(all devices)
3. Related link section, tablet portrait mode (768px), social links should appear on a next link after the text 
	and button. Currently, they are placed next to each other and icons are too small (Tablet)-->learn-more
4. You may be interested section heading is sticking to left edge on 1024px screen size(Tablet)-->related-stories

Feature branch:224-stories-article-remaining-issues
testing page:
https://224-stories-article-remaining-issues--danaher-abcam--aemsites.hlx.page/en-us/stories/articles/how-better-antibodies-can-save-time-in-the-lab
 main branch page:
https://main--danaher-abcam--aemsites.hlx.page/en-us/stories/articles/how-better-antibodies-can-save-time-in-
