### ISSUE TITLE
[Font] Not loading on CORS

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#226]
stories:1 Access to font at 'https://fonts.gstatic.com/s/notosans/v36/o-0bIpQlx3QUlC5A4PNB6Ryti20_6n1iPHjc5a7du3mhPy0.woff2' from origin 'https://www.abcam.com' has been blocked by CORS policy: Request header field pragma is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by Meenu-GSPANN** [comment]
This was a intermittent issue, Not appearing currently.
