### ISSUE TITLE
[Post Release] Podcast Detail Page

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#232]
[VALIDATE BEFORE START]

- [x] In addition to the common changes listed above for the hero module, the text 'Listed to audio' before the play icon is missing 
- [x] [NEWLY ADDED] Please check the tablet version (768px), look into video thumbnail size and alignment at multiple place is misaligned

**Comment by Rajesh-GSPANN** [comment]
Hi,
Task 1: have been fixed.

**Comment by Naveen-Ramgiri** [comment]
Task 2: Video thumbnail size and alignment at multiple place is misaligned, I have fixed this issue and shared the code with Rajesh and he updated the PR.
