### ISSUE TITLE
[Navigation] On the Header, change to temp menu

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#235]
Hi,

Can we please keep the exsiting menu code ( this will be used for 2.0 ), but implement the temp menu drop down to match abcam.com.  This can just be a hardcoded html file to list out the data.  It will appear on hover.

The drop down menu we built here, but it needs to be merged into the current header/navigation.  The search and everything else will stay the same.

https://fix-header-navigation--danaher-abcam--aemsites.aem.page/en-us

**Comment by Rajesh-GSPANN** [comment]
Hi @rgravitvl,
I have raised the PR. Can you please have a look at it and merge.

CC: @davenichols-DHLS @pardeepgera23 @Meenu-GSPANN

**Comment by Rajesh-GSPANN** [comment]
Hi @davenichols-DHLS ,
As discussed I have made the changes , can you have a look at it please.

CC: @Meenu-GSPANN @pardeepgera23 @shivangi1422 @rgravitvl
