### ISSUE TITLE
Related Links - Sticky left navigation

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#259]
Sticky left navigation to list related links on guide detail page and individual chapter page.

The Related Links block is a list of links that the author will manage for each page.  The author will edit the block on the page and add a title and URL link.

**Comment by amlan18041996** [comment]
[ 16-10-2024 ]: Sticky-Navigation along with styling implemented. Fetching all data from query-index.json as of now.
