### ISSUE TITLE
[Config] New testing domain from beta.abcam.com to pp.abcam.com

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#265]

**Comment by Meenu-GSPANN** [comment]
@davenichols-DHLS Please let me know If I can close this ticket as I pp.abcam is already pointing to stage.

**Comment by davenichols-DHLS** [comment]
Yes, I will close, thanks @Meenu-GSPANN .  However, I have another task open, as the sitemap is not working.
