### ISSUE TITLE
[Webinar] Detail Page(New User)

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#288]
- [x] Back to Navigation
- [x] Column
- [x] Title
- [x] Text
- [ ] Eloqua Form[Partialy completed]
- [x] Speakers[Sharan is working]
- [x] Learn More
- [x] Columns(More Episode)
- [x] RelatedStory (You may be interested in)

**Comment by venkateshamkeerthi** [comment]
completed development for related-story  components, and raised PR with issue #174 ,
will test functionality once that webinar page index completed
