### ISSUE TITLE
[Guides] Install and use the ITC Lubalin Graph Font for titles

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#299]
https://www.abcam.com/fonts/lubalingraphstd-demi.woff2

**Comment by davenichols-DHLS** [comment]
@rgravitvl  / @Meenu-GSPANN  - I created this task.

**Comment by Meenu-GSPANN** [comment]
> @rgravitvl / @Meenu-GSPANN - I created this task.

Sure Dave, will discuss for more details
