### ISSUE TITLE
Header Language/Country Selector

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#360]
Language/Country Selector

**Comment by rgravitvl** [comment]
@Meenu-GSPANN , I would suggest to split this task into 3 like My Account, Cart Icon and Country Selector. Each task can be assigned to individuals. One task could be assigned to either me or @sharanagoudapatil as well. 

CC - @davenichols-DHLS and @Rajesh-GSPANN

**Comment by sharanagoudapatil** [comment]
@Meenu-GSPANN - Header 'My Account' task I'll create a separate task and work. Let @kumarshoolam and @Rajesh-GSPANN can continue on Cart Icon & Language/Country Selector tasks. Thanks.

**Comment by Rajesh-GSPANN** [comment]
Hi @Meenu-GSPANN ,
Implemented country selector with all the countries and pushed the changes to feature branch.
https://360-header-cntry-acc-crt--danaher-abcam--aemsites.hlx.page/en-us/technical-resources/guides

**Comment by Rajesh-GSPANN** [comment]
Hi @davenichols-DHLS ,
I have implemented the changes as you requested for
1. Made it scrollable 
2. navigate using keyboard - down arrows to select and then press enter.

CC: @Meenu-GSPANN @pardeepgera23 @rgravitvl @sharanagoudapatil

**Comment by davenichols-DHLS** [comment]
> Hi @davenichols-DHLS , I have implemented the changes as you requested for
> 
> 1. Made it scrollable
> 2. navigate using keyboard - down arrows to select and then press enter.
> 
> CC: @Meenu-GSPANN @pardeepgera23 @rgravitvl @sharanagoudapatil

Thanks, but sorry when I type A or something then it lists a massive:

![image](https://github.com/user-attachments/assets/614773ac-fba0-4fa4-91dd-c05fdfec1166)

**Comment by Rajesh-GSPANN** [comment]
Hi @davenichols-DHLS ,
I have made the changes as requested . Can you please have a look at it and let me know.

CC: @Meenu-GSPANN @pardeepgera23 @sharanagoudapatil

**Comment by davenichols-DHLS** [comment]
Thank you, this is brilliant, if you can please add the code, so that China and Japan redirect to their websites then that would be perfect, and we can merge.  Thanks.

**Comment by Rajesh-GSPANN** [comment]
Hi @davenichols-DHLS ,
Redirection for the countries China and Japan is in place, so I have raised [PR](https://github.com/aemsites/danaher-abcam/pull/407). 
May I know are if you are expecting something else on this redirection? I can update the PR

CC; @Meenu-GSPANN @pardeepgera23 @sharanagoudapatil
