### ISSUE TITLE
Header Cart Icon 

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#386]
**Cart Icon:**
 
![image](https://github.com/user-attachments/assets/f981779d-4caf-43ab-ac08-a74296c8f0c4)

 
The cart icon is driving from the API to the eCommerce system.  These all start with proxy-gateway.abcam.com and are looked up from the “shoppingBasketId” local storage session:
![image](https://github.com/user-attachments/assets/902b2fd7-7554-4075-b739-c378128e3bd9)
 
Using the “shoppingBasketId” local storage session you can then call the eCommerce function, for example, to get the cart add the basket ID and country:
 
https://proxy-gateway.abcam.com/ecommerce/rest/v1/basket/XXXXXXXX?country=XX
 
In my case, I have this:

https://proxy-gateway.abcam.com/ecommerce/rest/v1/basket/5ce2cd5c-0950-4bdf-a8fc-47eb602e37eb?country=GB
 
This then returns a list of items in my cart.  Based on the number of items, that is what displays on the cart icon:
![image](https://github.com/user-attachments/assets/fc18e4e8-e2bb-42c6-8382-1ceb9e0f0d38) 
 
At this point, we should code in the option to pick up the number of items and show in the cart, but clicking on the icon should take you to the basket:
 
This again is based on “shoppingBasketId” local storage session and country selection:
 
https://www.abcam.com/en-us/shopping-basket/XXXXXXXXXXX?country=XX
 
As an example, mine is:
 
https://www.abcam.com/en-us/shopping-basket/5ce2cd5c-0950-4bdf-a8fc-47eb602e37eb?country=GB

**Comment by kumarshoolam** [comment]
Started Working on Header Cart Icon #386, Connected with Rajesh & taken required inputs, relevant stuff regarding the task and working around it.

**Comment by kumarshoolam** [comment]
- I have worked on Header Cart Icon and Completed the UI Part for desktop, working on responsive for the Cart Icon UI part.
- 
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/93937c4c-b01c-4707-b8e4-b3a28074f1bd">

**Comment by kumarshoolam** [comment]
- Worked on Responsive part for the Header Cart Icon - Completed, And as we are having dependency of BE about, which parameters should use.
- Meanwhile using the dummy Json to show the cart count in UI - In-Progress.

https://github.com/user-attachments/assets/39113eeb-7c41-47fa-ae74-e9268c62b4a4

**Comment by kumarshoolam** [comment]
- Mock Json has been Created for the Header Cart as the JSON provided in the Screenshot which mentioned in the e-mail.
