### ISSUE TITLE
[Stories] Podcasts Header

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#387]
We can remove the additional header/title on the podcast’s pages.  In this case, we can remove the ‘colliderscope’ section at the top, and then the title/image under can be the standard title block.

![image](https://github.com/user-attachments/assets/5414d411-71fb-4f3c-948f-2b6bdaacd7ce)

**Comment by sharanagoudapatil** [comment]
@davenichols-DHLS - As discussed, I've updated the podcast pages by removing 'Title Card' section from the UE author pages and republished them. Please have a look. Thanks.

CC - @rgravitvl and @Meenu-GSPANN

**Comment by sharanagoudapatil** [comment]
After removing the 'Title Card' from podcast pages, made template level (stories.js) code change also and now the pages looks fine. Thanks.
