### ISSUE TITLE
Header Notification Banners

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#388]
[Yeti Header Nav Banners.pdf](https://github.com/user-attachments/files/17688086/Yeti.Header.Nav.Banners.pdf)

Three different styles were created, designed for different uses cases, ideally user controlled so they are non-destructive to their navigation experience and any action required by the user.  
 
Homepage/sitewide navigation banners in our black branding nested with the global navigation
User notification banners
Informative messages in ‘light blue’
positive messages in ‘green’
Error messages in ‘red’ and for
Cautionary messages ‘amber’
User toast banners
informative messages in ‘light blue’
positive messages in ‘green’
Error messages in ‘red’ and for
Cautionary messages ‘amber’

**Comment by VSriPalivela** [comment]
Analysis Completed started development currently working on Block Creation.

**Comment by VSriPalivela** [comment]
Completed UE Block changes for initial development and started working on the Logic

**Comment by VSriPalivela** [comment]
Working on the functionality, Currently focused on developing and refining the core features to ensure everything functions smoothly and efficiently.

**Comment by VSriPalivela** [comment]
Completed the 90% Functionality, Working on remaining along with Styling the block

**Comment by VSriPalivela** [comment]
Completed 100% Functionality and Styling for desktop, responsiveness styling is in progress

**Comment by shivangi1422** [comment]
Working on including the header-notification(alert-banner) before header. We may need to change the approach by adding the styling in header.js.
