### ISSUE TITLE
[Protocols] Analyze The Pages

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#393]
Analyze the pages and document your findings.

https://www.abcam.com/en-us/technical-resources/protocols

**Analysis:**

- Hub Page => Same as guide template

- Detail Page:

	Left navigation =>	Chapters
						Related links
	Right navigation(Sections) => replace with Jump To Section

- Detail chapter page => 	1. modified/publish date(page metadata)
						2. timeline block for protocols
						3. Tab block(new) => Need to change background color based on icons

**Comment by vishnu-gspann** [comment]
Started analysing the pages
**Major findings:**
Hub page --  Same as guides template
Child page
chapters --> modified/publish date (New block required)
		     timeline block for protocols(Add additional functionality to existing block)
Yet to explore the related links under chapters

**Comment by vishnu-gspann** [comment]
Hi @Meenu-GSPANN ,
I have analyzed the protocols pages and below are the final findings.

- Hub Page => Same as guide template

- Detail Page:

      Left navigation =>	
            1. Chapters
            2. Related links
      Right navigation(Sections) => replace with Jump To Section

- Detail chapter page => 	
      1. modified/publish date(page metadata)
      2. timeline block for protocols
      3.Tab block(new) => Need to change background color based on icons

Adding same to the ticket description. If there any new things, I will update and closing the ticket for now.

**Comment by Meenu-GSPANN** [comment]
Created development stories after the analyzation.
