### ISSUE TITLE
ON HOLD [SEO] Core Web Vitals LCP and CLS

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#396]
•	LCP is high on many pages

**CLS:**
https://pagespeed.web.dev/analysis/https-www-abcam-com-en-us-technical-resources-guides-antibody-basics-antibody-basics/gas93jsaxm?form_factor=mobile

**Comment by Naveen-Ramgiri** [comment]
I have gone through an article on improving CLS and FCP scores and made some changes accordingly. I added the font-family directly in head.html and updated the rel="stylesheet" attribute for styles.css to rel="preload". However, to verify the Core Web Vitals status, these changes need to be deployed to the live environment. The highlighted section in the screenshot shows the CWV status based on real user data, which is available only for live URLs and not for feature branch URLs or local environments.

![Capture](https://github.com/user-attachments/assets/c06d11f8-d050-4684-8a1f-0c7edef51146)

**Comment by Meenu-GSPANN** [comment]
Dave will check with Markus if we really need to fix or improve over the current score

**Comment by pardeepgera23** [comment]
Current web vitals are all green..so closing this issue
