### ISSUE TITLE
[BigFix]  For the list of items in the index, can you please ignore "| Abcam"

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#397]

**Comment by pardeepgera23** [comment]
@sharanagoudapatil - Please remove toLowerCase() in breadcrumb and chapter-links, the same way as done in prod and create a new PR to move this change for stage.

**Comment by sharanagoudapatil** [comment]
I've removed toLowerCase() in breadcrumb and chapter-links js files and updated accordingly. Thanks.
