### ISSUE TITLE
ON HOLD: PDP Popup: Recommended Products and Recently Viewed - Review and Ratings

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#41]
Reviews and Ratings on the PDP drawer.
https://www.abcam.com/en-in/products/primary-antibodies/histone-h3-antibody-nuclear-marker-and-chip-grade-ab1791#drawer=recently-viewed&previewProductCode=ab8227&drawerView=reviews

![image](https://github.com/user-attachments/assets/00f9f0b3-7bae-42d2-bca2-20e49055dc2d)

**Comment by Rajesh-GSPANN** [comment]
Hi @davidzochowski ,
During our discussion, we determined that the Reviews and Ratings are fetched from a separate endpoint, which presents challenges in integrating the data into our system. As a result, we have decided to temporarily set aside the Reviews and Ratings section and will revisit it once we have the necessary details.


CC: @davenichols-DHLS @rgravitvl @Meenu-GSPANN @pardeepgera23 @amlan18041996 @venkateshamkeerthi @Naveen-Ramgiri

**Comment by Meenu-GSPANN** [comment]
Closing the issue due to the design changed
