### ISSUE TITLE
[Pathways] - Analysis for pathways pages

### ISSUE THREAD

**Issue by shivangi1422** [aemsites/danaher-abcam#415]
This story is regarding the analysis for the pathways hub, detail and chapter pages.

https://www.abcam.com/en-us/technical-resources/pathways

Please follow the figma designs similar to guides.

https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Optimus-%2F-Abcam-Website-Designs?node-id=3192-198&node-type=canvas&t=aP9ihvq7tvZKIVOf-0

**Comment by vishnu-gspann** [comment]
Hi @shivangi1422 .
I have analyzed the pathways pages and sharing my analysis. Please let me know if there is anything I need to update.

Hub page:- 
- 	Links with published/updated date and description
- 	pagination

Detail chapters page:
- 	Time stamp
- 	Rich text
- 	Jump to section
- 	Download
- 	References

Thanks

**CC:** @Meenu-GSPANN
