### ISSUE TITLE
[SEO] Core Web Vitals - Optimisation

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#419]
guide.js and guide.css is not loading at the same time, the css has a delay
Images on the page are loading eager on Guides pages and not lazy

**Comment by rgravitvl** [comment]
Separating undefined.plain.html from here and creating new one.

**Comment by vishnu-gspann** [comment]
Image loading issue have been fixed and looking into guide.js and guide.css loading issue

**Comment by vishnu-gspann** [comment]
Hi @davenichols-DHLS ,
I have analyzed few pages in guides and everything looks good for me. Image loading attribute is eager for 1st image of the page and lazy for other images. I think that is what we are expecting. 
If this is not what we are expecting, I request you to provide the pages that are having this image loading issues.
Thanks

**Comment by Meenu-GSPANN** [comment]
This issue is resolved now
