### ISSUE TITLE
Analyze the Applications Pages

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#429]
https://www.abcam.com/en-us/technical-resources/applications

**Comment by nagaraju-gspann** [comment]
The analysis of the application pages has been completed for a few pages, and no new blocks were identified. I will continue with the analysis of the remaining pages.

**Comment by nagaraju-gspann** [comment]
I have analyzed few pages under applications and those pages are redirecting to few main applications like protocols. I have gone through those pages as well and could not found new blocks except tabs and timeline.
Other differences are mentioned below:
https://www.abcam.com/en-us/technical-resources/protocols/cell-culture-and-maintenance-protocol ==> 3-level tab
https://www.abcam.com/en-us/technical-resources/protocols/mtt-assay ==> 2-level tab

**Comment by nagaraju-gspann** [comment]
Analyze the pages
https://www.abcam.com/en-us/technical-resources/applications

Analysis:
Hub page:
title card
Links

Hub tag page and detail page :
title card 
links

Chapter details page:
1.modified/publish date(page metadata)
2.Default text content
3.Jump to section
4.table
5.chapters
5.relatedlinks
6.button 
7.timeline
8.tab

For reference by tag :
Blocking                    --protocal
Cell analysis               --protocal
Cell culture                --protocal
Cellular assay              --protocal
ChIC/CUT&RUN-seq            --protocal
ChIP                        ---protocal/Troubleshooting
Conjugation                 --protocal
Dot blot                    --protocal
ELISA                       --protocal/Troubleshooting
Flow Cytometry              --protocal/Troubleshooting
Staining                    --protocal
Immunocytochemistry (ICC)   --protocal
Immunohistochemistry (IHC)  --protocal/Troubleshooting
Immunoprecipitation (IP)    --protocal/Troubleshooting
In Situ Hybridisation       --protocal
Western Blot                --protocal/Troubleshooting
Purification                --protocal
Zymography                  --protocal
Electrophoresis             --Troubleshooting

**Comment by Meenu-GSPANN** [comment]
Closing as its completed
