### ISSUE TITLE
[Bug] Live sitemap doesn't have WWW

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#444]
https://www.abcam.com/eds/sitemap-us.xml

**Comment by Meenu-GSPANN** [comment]
Dave will update the configuration in production

**Comment by davenichols-DHLS** [comment]
@Meenu-GSPANN  and @rgravitvl  - I checked, and the prod sitemap:  https://main--danaher-abcam-prod--aemsites.aem.page/eds/sitemap-us.xml  doesn't have the webinar pages nor the www prefix, it is like it hasn't been updating?
