### ISSUE TITLE
[Webinar] Issues With Breadcrumb || Form

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#450]
1. The breadcrumbs are not aligned to the rest of the page
2. The form section is not within the page width defined
3. The learn-more-wrapper is not aligned

**Comment by kumarshoolam** [comment]
**Ticket: [Webinar] Issues With Breadcrumb || Form || Learn More #450:**

- The breadcrumbs are not aligned to the rest of the page - Fixed
- The form section is not within the page width defined - Fixed

<img width="925" alt="image" src="https://github.com/user-attachments/assets/22140c0a-09c0-478f-832a-c522cede06d8">

- The learn-more-wrapper is not aligned - Fixed

<img width="939" alt="image" src="https://github.com/user-attachments/assets/46b3523e-6cd0-47a2-b6eb-158c8afb960a">
![image](https://github.com/user-attachments/assets/6dd3fdda-ec8d-4f8b-9aab-f782b89bdae9)
