### ISSUE TITLE
[PostImp] Header/Title Card and Breadcrumbs overlap to image 

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#499]

**Comment by Rajesh-GSPANN** [comment]
Hi @davenichols-DHLS ,
Have made the changes and raise PR: https://github.com/aemsites/danaher-abcam/pull/505
Can you please have a look at it.

@rgravitvl  @pardeepgera23 @shivangi1422  
Can you please review the code and Merge.

CC: @Meenu-GSPANN @Naveen-Ramgiri

**Comment by pardeepgera23** [comment]
Merged to prod repo as well..Closing the issue
