### ISSUE TITLE
[PostImp] Webinar Feedback

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#506]
- [ ] •	Are we still planning on ungating on-demand webinars? If so we won't need the form or the 'register now' button. Event pages are different and will have forms and be tagged as 'upcoming'. All of these webinars can be tagged as 'On-demand webinars'. If we’re still going with ungating, the videos will need to be added.
- [ ] •	Please use title case for all titles and headings, ie change 'OnDemand Webinar' to 'On-demand webinar'
- [x] •	Formatting of the sections is strange, the sections are on the right, the button is over the text (showing in both Edge and Chrome)  Now fixed this
- [ ] •	Remove downloads section
- [ ] •	Remove mentions of null, can that section be removed if the information isn't provided? 
- [ ] •	More episodes don't link anywhere, can we remove these as they aren't part of the series?

**Comment by pardeepgera23** [comment]
Merged to prod repo as well..Closing the issue
