### ISSUE TITLE
[PostImp] On Knowledge Center cards, the & symbol is shown

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#507]
![image](https://github.com/user-attachments/assets/d9f0a65f-f40c-47aa-a0ff-76c3b4d97c95)

![image](https://github.com/user-attachments/assets/1d713d21-1ac1-472f-8592-176633793e19)

**Comment by davenichols-DHLS** [comment]
@rgravitvl  / @sharanagoudapatil  / @Meenu-GSPANN  / @shivangi1422  / @Meenu-GSPANN  / @pardeepgera23  - low priority, but logging the issue.

**Comment by Naveen-Ramgiri** [comment]
When we give & symbol and space in the page metadata we are getting &amp; in the web page but we give & symbol in ay of our block then it's displaying as & only. Needs to correct with Markus to address this issue.

**Comment by Meenu-GSPANN** [comment]
Implemented a workaround by changing the page properties
