### ISSUE TITLE
Update CTA Banner Description

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#525]
https://www.abcam.com/en-us/support

**Comment by nagaraju-gspann** [comment]
The development is finished, but I am facing some issues with the response that need to be resolved.

**Comment by nagaraju-gspann** [comment]
I have raised PR .

**Comment by nagaraju-gspann** [comment]
As per the discussion with Sunny,
- Irrespective of description, The when text and button is placed side by side, the gap is 32px. 
- And when text and button are vertically stacked, gap is 24 px.
CC: @Meenu-GSPANN, @shivangi1422
