### ISSUE TITLE
[Guides] Padding/Spacing Issue In The Related Links Section

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#539]
https://www.abcam.com/en-us/technical-resources/guides/elisa-guide
![image](https://github.com/user-attachments/assets/6f5bb6f8-550d-47a7-9937-abfbe923234a)

**Comment by kumarshoolam** [comment]
Addressed the issues, Fixed and raised PR.

https://github.com/aemsites/danaher-abcam/pull/546

CC: @Meenu-GSPANN , @pardeepgera23 , @shivangi1422
