### ISSUE TITLE
[Support] Card Component Variation 

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#542]
https://www.abcam.com/en-us/support

![image](https://github.com/user-attachments/assets/d857cf98-8a0a-487a-8f2c-1e64156d53cb)

**Comment by kumarshoolam** [comment]
- Implemented 2 Card Component Variations based on the updated Figma design shared by Sunny. 
- While the major development is finished, some minor CSS adjustments are still required.

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/3b4ea351-3a1f-42da-b48c-536376f57430">

CC: @Meenu-GSPANN , @shivangi1422

**Comment by kumarshoolam** [comment]
Implemented/Developed the 2 Cards Variation - 542.
PR: https://github.com/aemsites/danaher-abcam/pull/585
CC: @Meenu-GSPANN , @shivangi1422, @pardeepgera23
