### ISSUE TITLE
'Jump to Section' component Enhancement

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#571]
Here are the requested changes to the 'Jump to Section' component. These updates are part of the Cross-sell and Support page design enhancements. The changes includes:
 
The sticky bar should appear only after the user scrolls past a specific section of the page, such as the header or elements like the pills used to select antibodies on cross-sell pages.
The sticky bar should not be visible by default when the page initially loads.
The sticky bar should extend across the entire width of the device, from edge to edge.
It differs from its current placement, which is placed on the top of the right column, as seen on the guides page.

**Comment by Rajesh-GSPANN** [comment]
Hi ,
Started working on it, first focusing on guides pages. Then will progress on.

CC; @Meenu-GSPANN @pardeepgera23 @shivangi1422

**Comment by Rajesh-GSPANN** [comment]
Hi @Meenu-GSPANN ,
I have made the changes in the Guide pages . I will confirm with the team, if that looks good will make the changes on the other pages as well.

CC: @pardeepgera23  @shivangi1422
