### ISSUE TITLE
CTA Banner CSS changes

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#579]
Irrespective of description, the when text and button is placed side by side, the gap is 32px. And when text and button are vertically stacked, gap is 24 px.

1. **With Description:**
  Till Mobile Screens the space between Description and CTA should be 24px. 
  From ipad to till large screens: It should be 32Px between Description and CTA .

2. **Without Description:** 
 Till Mobile Screens the space between Title and CTA should be 24px.

**Comment by nagaraju-gspann** [comment]
The PR has been successfully raised and approved.
