### ISSUE TITLE
[Bug] Some pages blank on Firefox

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#606]
https://www.abcam.com/en-us/knowledge-center/western-blot/western-blot-membranes

![image](https://github.com/user-attachments/assets/cad9630b-9623-411c-8491-7c9a54b200af)

**Comment by pardeepgera23** [comment]
This is happening due to empty image block added on the page. Corrected the authoring on stage environment by removing empty image block from page and now the page is opening fine on Firefox.

**Comment by shivangi1422** [comment]
The changes are done in prod as well. The default image was empty, hence removed the block from the page and republished it. The issue is resolved. Validated all the other pages as well in knowledge-center.
