### ISSUE TITLE
[UE] Cards For All Pages Implementation

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#71]
Figma Design:-
https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Primary-Antibodies-Landing-Page?node-id=252-28&t=oNLbv7ehIhFSQENE-1

**Comment by venkateshamkeerthi** [comment]
Analysis has completed,
require to add variation(3 Column-Article" in component-model. js file to differentiate existing "3 Columns"  Option.
changes required to add/modify styles in cards component for Article Cards

**Comment by venkateshamkeerthi** [comment]
looks @rgravitvl  has already implemented for article page(related-stories)
ref page: https://related-stories-block--danaher-abcam--aemsites.hlx.live/en/stories/articles/attitude-is-everything
need to implement same for Films and Podcast pages.
Need the query details for Films and Podcast page "You may also be interested in...) content
@rgravitvl @shivangi1422 @davenichols-DHLS

**Comment by venkateshamkeerthi** [comment]
as I discussed with ravi  and shivangi similar functionality has implemented for related stories using lifescience data(article index).
now abcam film and prodcast data is not ready , we are holding this tasking until abcam Film and Prodcast  pages are ready.

**Comment by Meenu-GSPANN** [comment]
Fixed with Related component story.
