### ISSUE TITLE
[UE] Title-Card Podcast Implementation

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#72]
Figma Design:-
https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Primary-Antibodies-Landing-Page?node-id=252-28&t=oNLbv7ehIhFSQENE-1

**Comment by VSriPalivela** [comment]
Completed Analysis started working on the development and completed model changes logic changes are in progress
