### ISSUE TITLE
[Stories] Other Episodes Podcast Implementation

### ISSUE THREAD

**Issue by Meenu-GSPANN** [aemsites/danaher-abcam#74]
Figma Design:-
https://www.figma.com/design/0MPkm5mzMfI0UPS6DWdbKs/Primary-Antibodies-Landing-Page?node-id=252-28&t=oNLbv7ehIhFSQENE-1

**Comment by Naveen-Ramgiri** [comment]
Completed the Analysis and started working on the Component modelling part.

**Comment by Naveen-Ramgiri** [comment]
**Status:** Component modelling is completed raised the PR and started developing the block logic in my feature branch.

**Comment by Naveen-Ramgiri** [comment]
Working on the logic and DOM to develop the block in my feature branch.

**Comment by Naveen-Ramgiri** [comment]
I'm working on the logic to implement the block and authoring three icons, but I'm only seeing one icon. I'm facing a challenge with this issue.

**Comment by Naveen-Ramgiri** [comment]
Development of the block desktop/mobile almost completed, facing issues with play and pause icons show/hide logic.
