### ISSUE TITLE
[Tasks]  Review Backlog tasks to see if we can add any

### ISSUE THREAD

**Issue by davenichols-DHLS** [aemsites/danaher-abcam#90]
https://adobe-dx-support.enterprise.slack.com/files/U04N8J8FL1M/F07K3LT7S4S/abcam_backlog_commercial_for_gspann.xlsx

**Comment by Meenu-GSPANN** [comment]
Thanks Dave, I am working with the team and analyzing the Webinar, Training and Corporate pages

**Comment by Meenu-GSPANN** [comment]
Created enough tasks for now
